### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by ianphil** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#10]
### Description

As a ‹role›, I'd like to ‹feature short description› [ , in order to ‹value it adds›. ]

### Acceptance Criteria

* [ ] Should ‹testable condition that should be satisfied›
* [ ] Should ‹testable condition that should be satisfied›
* [ ] …

### Tasks

* [ ] I'll do this
* [ ] then that
* [ ] …
