### ISSUE TITLE
Create Player

### ISSUE THREAD

**Issue by randguth** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#11]
# Create Player

## Description

As a Player I would like to create my player account so that I can begin to play the game. Each player begins with an empty wallet and a quantity of 3 of each kind of food and wearing a white tee-shirt.

## Acceptance Criteria

* [ ] Credentials created and stored
* [x] Default player characteristics and inventory values set
* [x] Food ie:
* [x] Banana
* [x] Jello
* [x] Pizza
* [ ] Clothing ie:
* [x] White tee-shirt
* [x] Tray
* [x] Raincoat
* [ ] Player default stats visible

### Tasks

* [ ] I'll do this
* [ ] then that
* [ ] …

**Comment by akazlow** [comment]
user will randomly be given 3 items from the food list and a random clothing item
