### ISSUE TITLE
Configure Player

### ISSUE THREAD

**Issue by randguth** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#13]
# Configure Player

## Description

As a Player I would like to customize my profile so that I can successfully challenge an opponent

## Acceptance Criteria

* [x] Player is able to successfully log into game
* [x] Player is able to see their "stats"

### Tasks

* [ ] I'll do this
* [ ] then that
* [ ] …
