### ISSUE TITLE
Lunch Money and Health

### ISSUE THREAD

**Issue by randguth** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#14]
# Lunch Money and Health

## Description

As a Player I would like the lunch money and health I receive each day to be added to my wallet and my health counter

## Acceptance Criteria

* [ ] Every 24 hours, and at the same time for each player, an identical fixed amount is added to each registered player's wallet and health accounts
* [ ] When a player logs into the game the new total amount appears in their stats
* [ ] A player does not have to log in daily to get lunch money and health for each day

### Tasks

* [ ] I'll do this
* [ ] then that
* [ ] …
