### ISSUE TITLE
Enter Cafeteria

### ISSUE THREAD

**Issue by randguth** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#15]
# Enter Cafeteria

## Description

As a Player I would like to enter the cafeteria so that I can see who is available to fight

## Acceptance Criteria

* [ ] A logged-in Player is able to enter a command that changes their status to "in the cafeteria"
* [x] The Player is able to see a list of all other player/opponents that are currently in the cafeteria (available to fight)
* [ ] The Player is able to enter a command and leave the cafeteria and return to their profile configuration page

### Tasks

* [ ] I'll do this
* [ ] then that
* [ ] …
