### ISSUE TITLE
Configure Game

### ISSUE THREAD

**Issue by randguth** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#17]
# Configure Game

## Description

As a Game Administrator I want configure the game so that players can join and fight

* set max number of throws in a fight
* set amount of daily lunch money
* set time lunch money is paid

## Acceptance Criteria

* [ ] Admin is able to set game parameters upon game creation
* [ ] Admin is able to edit parameters once a game is started without affecting leaderboard or individual player stats

### Tasks

* [ ] I'll do this
* [ ] then that
* [ ] …
