### ISSUE TITLE
Join Fight

### ISSUE THREAD

**Issue by randguth** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#18]
# Invite Players

## Description

As a player, I want join other players in the food fight.

* Connect to the ongoing game with players
* Receive a list of players in the player who are already in room who can be engaged in the fight.
* If the player is the first person in the room, no players are shown

## Acceptance Criteria

* [x] Player is able to join the fight by connecting with the bot
* [x] Player identifies self, or is identified by the system (channel)
* [x] Player gets a list of players in the room.

### Tasks

* [x] I'll do this
* [x] then that
* [x] …

**Comment by jamesptruitt** [comment]
List Player status created
